server.port: ${vcap.application.port:8761}
spring.cloud.config.server.prefix: /config

management:
  port: ${server.port}

info:
  group: @project.groupId@
  artifact: @project.artifactId@
  name: @project.name@
  description: @project.description@
  version: @project.version@
  stage: ${spring.profiles.active}

security.user.password: '{cipher}b41023644bca630173be9ef89a38fb0c8798f059a65258cb29f057afef18fa23'

---
################################ DEV PROFILE ######################
spring:
  profiles: dev

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false
    waitTimeInMsWhenSyncEmpty: 0

---
################################ DOCKER PROFILE ######################
spring:
  profiles: docker

eureka:
  instance:
    hostname: vbb-discovery
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://vbb-discovery:${server.port}/eureka/
  server:
    enableSelfPreservation: false
    waitTimeInMsWhenSyncEmpty: 0

#spring.cloud.config.discovery.enabled: true