server.port: ${vcap.application.port:8761}
spring.cloud.config.server.prefix: config

management:
  port: ${server.port}

security:
  user:
    name: '{cipher}51a0c7772cb362c79f0bb6f2d884cec7001ee523aa98ada57a7b68e269f948cdc9b4ef74abe61fc6be5115f4694eb588'
    password: '{cipher}b41023644bca630173be9ef89a38fb0c8798f059a65258cb29f057afef18fa23'

---
################################ DEV PROFILE ######################
spring:
  profiles: dev

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
  server:
    #responseCacheUpdateIntervalMs: 500
    #evictionIntervalTimerInMs: 500
    enableSelfPreservation: false

---
################################ DOCKER PROFILE ######################
spring:
  profiles: docker

eureka:
  instance:
    hostname: vbb-discovery
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://vbb-discovery:${server.port}/eureka/
  server:
    enableSelfPreservation: false
    waitTimeInMsWhenSyncEmpty: 0

#spring.cloud.config.discovery.enabled: true
