# Hystrix
hystrix:
  enabled: false
  command.default.execution.timeout.enabled: false

############  Actuator properties #############
management:
  port: ${server.port}
############  END Actuator properties #############

vbb.app:
  users:
    boborel: '{cipher}b9b9d3b02e3b1c03aaf98ce78970e1e51b320f8a854d9206cce10a31c8a106a3295a0929ba36ffafc201e27dc746f2fd7768a32f39f2003551d85eb9030094d3'
  basic.authentication: '{cipher}53329d2fb6c7c439c5dea14de5ddcb3c710bba4d48dd89dc5d3834a347dee9765122fbd02ef323b090becfe281fbe4a4'

management.security.roles: ACTUATOR

---
################################ DEV PROFILE ######################
spring:
  profiles: dev

eureka:
  instance:
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
    leaseRenewalIntervalInSeconds: 3
    leaseExpirationIntervalInSeconds: 5
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    registerWithEureka: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${vbb-discovery.credentials.uri:http://127.0.0.1:8761}/eureka/

---
spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://vbb-discovery:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 3
    leaseExpirationIntervalInSeconds: 5
    preferIpAddress: true
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}

---
################################ AWS PROFILE ######################
spring:
  profiles: aws

logging:
  level:
    ROOT: INFO
    #org.springframework.security: INFO

eureka:
  instance:
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
  environment: test
  datacenter: cloud
  client:
    eurekaServerDNSName: test.vbb.com
    region: eu-central-1
    registerWithEureka: true
    fetchRegistry: true
    eurekaServerURLContext: eureka
    eurekaServerPort: 80
    useDnsForFetchingServiceUrls: true
