server:
  port: ${VBB_GATEWAY_PORT:8092}

zuul:
  ignoredServices: "*"
  add-proxy-headers: true
  routes:
    api-services:
      path: /api-services/**
      serviceId: vbb-api-services
      stripPrefix: false
    discovery:
      path: /discovery/**
      serviceId: vbb-discovery
    diffusion:
      path: /api-diffusion/**
      serviceId: vbb-diffusion
      stripPrefix: false
    vbb-user:
      sensitiveHeaders:
      path: /uaa/**
      serviceId: vbb-user
      stripPrefix: false

# Hystrix
hystrix.command.default.execution.timeout.enabled: false
ribbon:
  ConnectTimeout: 40000
  ReadTimeout: 40000

spring:
  aop:
    proxy-target-class: true
  freemarker:
    cache: false
    
security.user.name: boborel
security.user.password: '{cipher}dbf312e6f4393b8b7527a907a5319efd3c4f7d098a9bd65d2b6a98408a0484e9'

---
################################ DEV PROFILE ######################
spring:
  profiles: dev

eureka:
  instance:
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    leaseRenewalIntervalInSeconds: 3
    leaseExpirationIntervalInSeconds: 5
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    registerWithEureka: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${vbb-discovery.credentials.uri:http://127.0.0.1:8761}/eureka/

diffusion:
  endpoints:
    - '{cipher}2faff49c8bb010a3e87357be9674be1658a19f4b7a9bca59a40ddb77c7ce3356'
---
spring:
  profiles: docker
  cloud:
    inetutils:
      ignored-interfaces:
        - eth0
        - eth1
        - eth2
        - eth3
        - lo
  resources:
    static-locations: classpath:/vbb-ui/
    
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://vbb-discovery:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
#    leaseRenewalIntervalInSeconds: 3
#    leaseExpirationIntervalInSeconds: 5
    preferIpAddress: true
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}

diffusion:
  endpoints:
    - '{cipher}f7379f068e40508b3e87d9b8e231239cb1ea2deb34f584dc6c09f994fe136f1a'
---
################################ AWS PROFILE ######################
spring:
  profiles: aws
  resources:
    static-locations: classpath:/static/ui/

server.port: 80

logging:
  level:
    ROOT: INFO
    #org.springframework.security: INFO

eureka:
  instance:
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
  environment: test
  datacenter: cloud
  client:
    eurekaServerDNSName: test.vbb.com
    region: eu-central-1
    registerWithEureka: true
    fetchRegistry: true
    eurekaServerURLContext: eureka
    eurekaServerPort: 8761
    useDnsForFetchingServiceUrls: true
