server:
  port: ${VBB_DISCOVERY_PORT:8761}

security:
  user:
    name: '{cipher}51a0c7772cb362c79f0bb6f2d884cec7001ee523aa98ada57a7b68e269f948cdc9b4ef74abe61fc6be5115f4694eb588'
    password: '{cipher}b41023644bca630173be9ef89a38fb0c8798f059a65258cb29f057afef18fa23'

management:
  context-path: /manage
  port: ${server.port}
  security.roles: ACTUATOR

---
################################ DEV PROFILE ######################
spring:
  profiles: dev

eureka:
  instance:
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
  client:
    registerWithEureka: true
    fetchRegistry: false
  server:
    #responseCacheUpdateIntervalMs: 500
    #evictionIntervalTimerInMs: 500
    enableSelfPreservation: false

---
################################ DOCKER PROFILE ######################
spring:
  profiles: docker
  cloud:
    inetutils:
      ignored-interfaces:
        - eth0
        - eth1
        - eth2
        - eth3
        - lo

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    hostname: vbb-discovery
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://vbb-discovery:${server.port}/eureka/
  server:
    enableSelfPreservation: false
#    evictionIntervalTimerInMs: 10000
#    waitTimeInMsWhenSyncEmpty: 0
---
################################ AWS PROFILE ######################
spring:
  profiles: aws

logging:
  level:
    ROOT: INFO
    #org.springframework.security: DEBUG

eureka:
  instance:
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
    metadataMap:
      configPath: /config
      user: '{cipher}200be6699cf9cdc2a7179ceb7e928efae3b6b2dccf490b73ef92bb2649fe90e370b100fda51290614dda6cf4cae5fbf3'
      password: '{cipher}1a54f43cebf2fd3beafe64f45fbd857446dfce5acaca45b0f618d4b4a693e926'
  environment: test
  datacenter: cloud
  client:
    eurekaServerDNSName: test.vbb.com
    region: eu-central-1
    registerWithEureka: true
    fetchRegistry: true
    eurekaServerURLContext: eureka
    eurekaServerPort: 8761
    useDnsForFetchingServiceUrls: true
  server:
    #responseCacheUpdateIntervalMs: 500
    #evictionIntervalTimerInMs: 500
    enableSelfPreservation: false
    aWSAccessId: '{cipher}ae2db650a8ddeef2b3d479795cb8487a6028896d7bd1adddc268edce0e380d4700cc233ab7e3d6fe011eb74c15a9c02e'
    aWSSecretKey: '{cipher}51936b8481256a804eb44eb9723d34d9f1d675ccc5622b26c7cc4da159b0a0e285440cca68f711574e9bb5c08ed75154f0effdb81536330631fd154611cf9abc'
    asgName: EC2ContainerService-vbb-dev-EcsInstanceAsg-76SU2ZP6WHJH
