spring.cloud.config.server.prefix: config

security:
  user:
    name: '{cipher}51a0c7772cb362c79f0bb6f2d884cec7001ee523aa98ada57a7b68e269f948cdc9b4ef74abe61fc6be5115f4694eb588'
    password: '{cipher}b41023644bca630173be9ef89a38fb0c8798f059a65258cb29f057afef18fa23'

management.security.roles: ACTUATOR

---
################################ DEV PROFILE ######################
spring:
  profiles: dev

eureka:
  instance:
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
  client:
    registerWithEureka: true
    fetchRegistry: false
  server:
    #responseCacheUpdateIntervalMs: 500
    #evictionIntervalTimerInMs: 500
    enableSelfPreservation: false

management:
  port: ${server.port}

---
################################ DOCKER PROFILE ######################
spring:
  profiles: docker

eureka:
  instance:
    hostname: vbb-discovery
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://vbb-discovery:${server.port}/eureka/
  server:
    enableSelfPreservation: false
    waitTimeInMsWhenSyncEmpty: 0

management:
  port: ${server.port}

#spring.cloud.config.discovery.enabled: true

---
################################ AWS PROFILE ######################
spring:
  profiles: aws

logging:
  level:
    ROOT: INFO
    org.springframework.security: INFO

eureka:
  instance:
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
  environment: test
  datacenter: cloud
  client:
    eurekaServerDNSName: test.vbb.com
    region: eu-central-1
    registerWithEureka: true
    fetchRegistry: true
    eurekaServerURLContext: eureka
    #eurekaServerPort: 8761
    useDnsForFetchingServiceUrls: true
  server:
    #responseCacheUpdateIntervalMs: 500
    #evictionIntervalTimerInMs: 500
    enableSelfPreservation: false
