server:
  port: ${VBB_SERVICES_PORT:8065}
  timezone: Europe/Bucharest
  
# Hystrix
hystrix:
  enabled: false
  command.default.execution.timeout.enabled: false


############  Actuator properties #############
management:
  context-path: /manage
  port: ${server.port}
############  END Actuator properties #############


############### async parameters for default executor
DefaultExecutor:
  corePoolSize: 2
  maxPoolSize: 8
  queueCapacity: 10000
############### end async parameters

vbb.app:
  users:
    boborel: '{cipher}8f18d3e9dffce1b4349482b6e019decc9a8f2bded14e6e10bfbc005eb197087f2a66038c2c24dc65172ddfa1d5ff54df'
  basic.authentication: '{cipher}53329d2fb6c7c439c5dea14de5ddcb3c710bba4d48dd89dc5d3834a347dee9765122fbd02ef323b090becfe281fbe4a4'

spring.mail:
  host: smtp.gmail.com
  port: 587
  username: '{cipher}4ef27383d6f69809ece1af3107cdf5484088a314ce2f3f8cac2aa69ffe8b2ef50051706c2a32d687f120237aa6f72f55'
  password: '{cipher}db66036111eab8079038a07800db2e13add138ddd747da9971d9ee222405765d'
  properties.mail:
    transport.protocol: smtp
    smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
    debug: false
mail.from: VirtualBetBuddy

# INTERNATIONALIZATION (MessageSourceAutoConfiguration)
spring.messages:
  basename: messages # Comma-separated list of basenames, each following the ResourceBundle convention.
  encoding: UTF-8 # Message bundles encoding.

# THYMELEAF (ThymeleafAutoConfiguration)
spring.thymeleaf:
  cache: true # Enable template caching.
  check-template-location: true # Check that the templates location exists.
  content-type: text/html # Content-Type value.
  encoding: UTF-8 # Template encoding.
  mode: HTML5 # Template mode to be applied to templates. See also StandardTemplateModeHandlers.
  prefix: classpath:/mails/ # Prefix that gets prepended to view names when building a URL.
  suffix: .html # Suffix that gets appended to view names when building a URL.

security.user.name: boborel
security.user.password: '{cipher}dbf312e6f4393b8b7527a907a5319efd3c4f7d098a9bd65d2b6a98408a0484e9'

flyway:
  enabled: true
  locations: classpath:db/migration

captcha:
  useproxy: false
  proxyhost:
  faiureurl: /
  privatekey: '{cipher}e7556863a465ee3a567740cdf97d913fbabd16979bdecf449705a3ae9da650900a6dbc88b7fea82bdf9bea3f20e0f214bfee09915440e4514a3fdaba5f3013e8'

---
spring:
  profiles: dev
  activemq:
    brokerUrl: tcp://127.0.0.1:61613
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/vbb
    username: root
    password: asd1234
    maxActive: 100
    testOnBorrow: true
    validationQuery: SELECT 1
  jpa:
    database: MYSQL
    show-sql: true
    properties.hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
      cache:
        use_second_level_cache: false
#        TODO de vazut cash distribuit in cloud
#        use_second_level_cache: true
#        use_query_cache: true
#        provider_configuration: classpath:ehcache.xml
#        use_structured_entries: true
#        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

eureka:
  instance:
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    leaseRenewalIntervalInSeconds: 3
    leaseExpirationIntervalInSeconds: 5
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    registerWithEureka: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${vcap.services.vbb-discovery.credentials.uri:http://127.0.0.1:8761}/eureka/
vbb.gateway.url: http://localhost:8092

---
spring:
  profiles: docker
  cloud:
    inetutils:
      preferredNetworks:
        - 10.0
      ignored-interfaces:
        - eth0
#  cloud:
#    inetutils:
#      ignored-interfaces:
#        - eth0
#        - eth1
#        - eth2
#        - eth3
#        - lo
  activemq:
    brokerUrl: tcp://vbb-diffusion:61613
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://vbb-mysql:3306/vbb
    username: root
    password: asd1234
    maxActive: 100
    testOnBorrow: true
    validationQuery: SELECT 1
  jpa:
    database: MYSQL
    show-sql: false
    properties.hibernate:
      format_sql: false
      dialect: org.hibernate.dialect.MySQLDialect
      cache:
        use_second_level_cache: false

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://vbb-discovery:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#    leaseRenewalIntervalInSeconds: 3
#    leaseExpirationIntervalInSeconds: 5
    preferIpAddress: true
#    hostname: ${HOST_NAME}
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

---
################################ AWS PROFILE ######################
spring:
  profiles: aws
  activemq:
    brokerUrl: tcp://52.28.179.159:61613
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://vbb-db.cxjcgxqqm6fl.eu-central-1.rds.amazonaws.com:3306/vbb
    username: root
    password: '{cipher}7a2ea55fb06bdb11d19a3ce08972fd18d5f2f963dd0ad39820479d68b7824335f70b1c2e0934dc413780ae0adfa9f3bd'
    maxActive: 100
    testOnBorrow: true
    validationQuery: SELECT 1
  jpa:
    database: MYSQL
    show-sql: false
    properties.hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
      cache:
        use_second_level_cache: false

logging:
  level:
    ROOT: INFO
    com.netflix.discovery.shared.resolver.aws: ERROR
    #org.springframework.security: INFO

eureka:
  instance:
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
  environment: test
  datacenter: cloud
  client:
    eurekaServerDNSName: test.vbb.com
    region: eu-central-1
    registerWithEureka: true
    fetchRegistry: true
    eurekaServerURLContext: eureka
    eurekaServerPort: 8761
    useDnsForFetchingServiceUrls: true
