logging:
  level:
    org.springframework:
#      security: DEBUG
      cloud:
        config.client.ConfigServicePropertySourceLocator: ERROR

spring.mail:
  host: smtp.gmail.com
  port: 587
  username: '{cipher}4ef27383d6f69809ece1af3107cdf5484088a314ce2f3f8cac2aa69ffe8b2ef50051706c2a32d687f120237aa6f72f55'
  password: '{cipher}db66036111eab8079038a07800db2e13add138ddd747da9971d9ee222405765d'
  properties.mail:
    transport.protocol: smtp
    smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
    debug: false
mail.from: VirtualBetBuddy

# INTERNATIONALIZATION (MessageSourceAutoConfiguration)
spring.messages:
  basename: messages # Comma-separated list of basenames, each following the ResourceBundle convention.
  encoding: UTF-8 # Message bundles encoding.

# THYMELEAF (ThymeleafAutoConfiguration)
spring.thymeleaf:
  cache: true # Enable template caching.
  check-template-location: true # Check that the templates location exists.
  content-type: text/html # Content-Type value.
  encoding: UTF-8 # Template encoding.
  mode: HTML5 # Template mode to be applied to templates. See also StandardTemplateModeHandlers.
  prefix: classpath:/mails/ # Prefix that gets prepended to view names when building a URL.
  suffix: .html # Suffix that gets appended to view names when building a URL.

management:
  port: ${server.port}
vbb.app:
  users:
    boborel: '{cipher}8f18d3e9dffce1b4349482b6e019decc9a8f2bded14e6e10bfbc005eb197087f2a66038c2c24dc65172ddfa1d5ff54df'

---
spring:
  profiles: dev
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 3
    leaseExpirationIntervalInSeconds: 5
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    registerWithEureka: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${vcap.services.vbb-discovery.credentials.uri:http://127.0.0.1:8761}/eureka/

---
spring:
  profiles: cloud
eureka:
  instance:
    #I do this because my services don’t use fixed DNS. APPLICATION_DOMAIN is an environment variable I set in my deploy scripts that tells a service what its externally referenceable URI is
    hostname: ${APPLICATION_DOMAIN}
    nonSecurePort: 80

---
spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://vbb-discovery:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 3
    leaseExpirationIntervalInSeconds: 5
    preferIpAddress: true
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
