# Hystrix
hystrix:
  enabled: false
  command.default.execution.timeout.enabled: false

vbb.app:
  users:
    boborel: '{cipher}5befb33659c72b2569005783dbbfda67766d5991d90ac5c5302dda8860f0bd5a70cb545a499fa7ce9a7c34c112c091906900174c9d0e869e59260fe628d83b0d'
  basic.authentication: '{cipher}53329d2fb6c7c439c5dea14de5ddcb3c710bba4d48dd89dc5d3834a347dee9765122fbd02ef323b090becfe281fbe4a4'

management.security.roles: ACTUATOR

---
################################ DEV PROFILE ######################
spring:
  profiles: dev

eureka:
  instance:
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
    leaseRenewalIntervalInSeconds: 3
    leaseExpirationIntervalInSeconds: 5
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    registerWithEureka: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${vbb-discovery.credentials.uri:http://127.0.0.1:8761}/eureka/

---
spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://vbb-discovery:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 3
    leaseExpirationIntervalInSeconds: 5
    preferIpAddress: true
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}

---
################################ AWS PROFILE ######################
spring:
  profiles: aws

logging:
  level:
    ROOT: INFO
    #org.springframework.security: INFO

eureka:
  instance:
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
  environment: test
  datacenter: cloud
  client:
    eurekaServerDNSName: test.vbb.com
    region: eu-central-1
    registerWithEureka: true
    fetchRegistry: true
    eurekaServerURLContext: eureka
    eurekaServerPort: 80
    useDnsForFetchingServiceUrls: true
